### ISSUE TITLE
Not highlighting variable values starting with letters

### ISSUE THREAD

**Issue by OskarPersson** [nex3/sass-mode#18]
For some reason variable values that starts with letters doesn't get highlighted.

![skarmavbild 2015-06-01 kl 20 10 23](https://cloud.githubusercontent.com/assets/935414/7919682/53377b5c-089a-11e5-8b1f-9b7b4f2e18b3.png)

**Comment by purcell** [comment]
I think you want `scss-mode`, not `sass-mode`.
