### ISSUE TITLE
CSS syntax auto-complete?

### ISSUE THREAD

**Issue by tr37ion** [nex3/sass-mode#19]
Hi, I can't get CSS syntax auto-complete working with SASS-mode. How about making sass-mode a minor mode?

**Comment by purcell** [comment]
> Hi, I can't get CSS syntax auto-complete working with SASS-mode. 

Please be more specific about what you're trying, what results you expect, and what's happening instead.

> How about making sass-mode a minor mode?

No, it has to be a major mode.

P.S. Just in case you're trying to use `scss` syntax, please note that you should be using `scss-mode`, not `sass-mode`.

**Comment by tr37ion** [comment]
Hi, thanks for the reply. The issue is that I want to use sass, but when I enable it ac for the css syntax is off. So, I can use sass-mode, but I miss ac the css words or I turn sass-mode off an get back css ac but no more sass identaion is provided.

**Comment by purcell** [comment]
You can do something like this (untested):

```el
(add-hook 'sass-mode-hook
          (lambda () (add-to-list 'ac-sources 'ac-source-css-property nil t))
```

**Comment by tr37ion** [comment]
Thanks, it works :)
