### ISSUE TITLE
No syntax colour in .sass file after loading file

### ISSUE THREAD

**Issue by oliverangelil** [nex3/sass-mode#23]
When I type sass code I see colour appear in real time in emacs, however when I reload a .sass file in emacs there's no colour anywhere. Is there a line I can add to my .emacs init file to see colour after loaded a file? Can one run another mode while sass-mode is running? For example could I run [web-mode](http://web-mode.org/) simultaneously to get some if its features?

**Comment by purcell** [comment]
What do you mean by "reload"? Please can you describe specific steps to reproduce this problem, starting with an Emacs instance launched with the `-Q` flag?

**Comment by hrkfdn** [comment]
Same problem here. I open up my Emacs desktop and it loads my .sass file, but only very few of the lines are colored, as visible here: https://i.imgur.com/0Dp7wtF.png

If I edit a line it will be colored accordingly. Newly written lines also seem fine.

**Comment by liZe** [comment]
I've removed `(require 'cl-lib)` at the beginning of the file, and it seems to fix the problem.

Don't ask me why, I don't know what cl-lib is. I've just read the *Messages* buffer and see that it was the source of the problem. This line is probably useful for something, but I don't know what.

**Comment by purcell** [comment]
> 've removed `(require 'cl-lib)` at the beginning of the file, and it seems to fix the problem.
> 
> Don't ask me why, I don't know what cl-lib is. I've just read the *Messages* buffer and see that it was the source of the problem. This line is probably useful for something, but I don't know what.

You've probably just downloaded this file without properly installing its dependencies, which include the `cl-lib`. That package is bundled in Emacs >= 24.3, but also available separately from GNU ELPA. In any case, there are no clues in any of these comments about how to reproduce the issue.

**Comment by liZe** [comment]
> You've probably just downloaded this file without properly installing its dependencies, which include the `cl-lib` library.

I've installed it with Emacs' package manager, just as the other packages. 

> That package is bundled in Emacs >= 24.3, but also available separately from GNU ELPA.

I've got the built-in `cl-lib` 1.0 (with Emacs 26.2).

> In any case, there are no clues in any of these comments about how to reproduce the issue.

Here are the steps to reproduce for me:
- Launch `package-list-packages`
- Install `sass-mode`
- Open a `.sass` file
- The color is applied to only a couple of lines (as in [the previous comment's screenshot](https://i.imgur.com/0Dp7wtF.png))

I get these errors in the `*Messages*` buffer:
```
Error during redisplay: (jit-lock-function 1) signaled (no-catch --cl-block-nil-- t)
Error during redisplay: (jit-lock-function 501) signaled (no-catch --cl-block-nil-- t)
```

As I've seen `--cl-block-nil` in this message, and as I've seen the `(require 'cl-lib)` at the beginning of my `~/.emacs.d/elpa/sass-mode-20161007.626/sass-mode.el` file, I've naively tried to remove the `(require 'cl-lib)` line. I've rebuild the package, restarted Emacs, and the syntax highlight works perfectly with no error message.

**Comment by purcell** [comment]
Thanks @liZe! Those details were really helpful, and while I wasn't able to reproduce this issue directly locally, I'm relatively confident that it will have been fixed by 247a0d4b. Perhaps you would be willing to try it out?

**Comment by liZe** [comment]
> Perhaps you would be willing to try it out?

It works, thanks a lot!

**Comment by purcell** [comment]
Great, thanks for confirming!
